# Generated by Django 5.1 on 2024-09-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('date_diagnosed', models.DateField()),
                ('medications', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Recovered', 'Recovered')], max_length=10)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
